#!/bin/bash

echo -e "\n\nＳｈａｄｅｓ  ｏｆ  ｇｒｅｙ (ｈｏｒｉｚｏｎｔａｌ)：\n"
if [ $COLUMNS -gt 95 ]; then
	h3count=232
	echo 2{32..55}
	while [ $h3count -lt 256 ]; do
		echo -en "\e[48;5;"$h3count"m   \e[m"
		echo -en " "
		h3count=$((h3count + 1))
	done
	echo -e "\n\n"
fi

