#!/bin/bash

__version__='1.2'

#echo -e "[38;5;0m[48;5;15m  "$xxx"  [m	"
#((xxx +=1))


function __cmap1()
{
	xxx=0
	echo -e "\n\n\033[01mＢａｓｉｃ ｃｏｌｏｒｓ：\033[m\n"
#	while [ "$xxx" -lt 17 ]; do
#		while [ "$xxx" -lt 8 ]; do
	figlet -c -w 62 -f term '[BOLD / BRIGHT]'
	echo
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
#			echo -e "BOLD / BRIGHT"
#		done
echo -en "\n"
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m"$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m"$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m"$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m"$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m"$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
			echo -en "[38;5;15m"$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
echo
echo
			figlet -c -w 62 -f term '[REGULAR]'
#			echo -e "NORMAL"
#			echo -e """
#NOTE:
#0 - 7  are the same as 30 - 37 WITHOUT bold
#8 - 15 are the same colors are 30-37, when used with 01 (BOLD)

#"""
#	done
}

function __cmap1a()
{
	xxx=0
	echo -e "\n\nＢａｓｉｃ ｃｏｌｏｒｓ：\n"
	while [ "$xxx" -lt 17 ]; do
		while [ "$xxx" -lt 10 ]; do
			while [ "$xxx" -lt 8 ]; do
				echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
				((xxx +=1))
			done
			echo -e "BOLD / BRIGHT"
			echo -en "[38;5;15m "$xxx":[48;5;"$xxx"m    [m "
			((xxx +=1))
		done
		echo -en "[38;5;15m"$xxx":[48;5;"$xxx"m    [m "
		((xxx +=1))
	done
	echo -e "NORMAL"
}


#echo

function __cmap2()
{
echo -e "\n\n\033[01mＥｘｔｒａ ｃｏｌｏｒｓ ：\033[m\n"
xxx=16
while [ $xxx -lt 231 ]; do
	while [ $xxx -lt 100 ]; do
		echo -en "[38;5;15m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -en "[38;5;15m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -en "[38;5;15m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -en "[38;5;15m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -en "[38;5;15m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -e "[38;5;15m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
	done
	echo -en "[38;5;15m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -en "[38;5;15m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -en "[38;5;15m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -en "[38;5;15m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -en "[38;5;15m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -e "[38;5;15m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
done
}

function __cmap3v(){
xxx=232
echo -e """\n\n\033[01mＳｈａｄｅｓ  ｏｆ  ｇｒｅｙ (ｖｅｒｔｉｃａｌ):\033[m
Note: \033[3mThe verticle version of this table is being
      displayed because the terminal is not wide
      enough to display the horizontal table prop-
      erly. To show the Horizontal table, increase
      the terminal's width to 96 cols or more.\033[m
"""

while [ $xxx -lt 256 ]; do
		echo -e "[38;5;15m "$xxx"   [48;5;"$xxx"m     [m  "
		((xxx +=1))
done

}

function __cmap3h(){
echo -e "\n\n\033[01mＳｈａｄｅｓ  ｏｆ  ｇｒｅｙ (ｈｏｒｉｚｏｎｔａｌ)：\033[m\n"
if [ $COLUMNS -gt 95 ]; then
	h3count=232
	echo 2{32..55}
	while [ $h3count -lt 256 ]; do
		echo -en "\e[48;5;"$h3count"m   \e[m"
		echo -en " "
		h3count=$((h3count + 1))
	done
	echo -e "\n\n"
fi
}
#
#xxx=232
#
#while [ $xxx -lt 256 ]; do
#		echo -e "[38;5;15m "$xxx"   [48;5;"$xxx"m     [m  "
#		((xxx +=1))
#done
#}
function __cmap(){
	__cmapall | less -r
}

function __cmapall(){
	__cmap1
	__cmap2
	if [ "$COLUMNS" -gt "95" ]; then
		__cmap3h
	else
		__cmap3v
	fi
}


function shades_grey(){
	g=232
	while [ $g -lt 256 ]; do
		echo -en "\033[38;5;15m\033[48;5;"$g"m "$g" \033[m\t"
		((g +=1))
		echo -en "\033[38;5;15m\033[48;5;"$g"m "$g" \033[m\t"
		((g +=1))
		echo -en "\033[38;5;15m\033[48;5;"$g"m "$g" \033[m\t"
		((g +=1))
		echo -e "\033[38;5;15m\033[48;5;"$g"m "$g" \033[m\t"
		((g +=1))
	done
}
