#!/bin/bash


echo -e "\n\nＥｘｔｒａ ｃｏｌｏｒｓ ：\n"
xxx=16
while [ $xxx -lt 231 ]; do
	while [ $xxx -lt 100 ]; do
		echo -en "[38;5;256m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -en "[38;5;256m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -en "[38;5;256m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -en "[38;5;256m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -en "[38;5;256m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
		echo -e "[38;5;256m "$xxx": [48;5;"$xxx"m      [m  "
		((xxx +=1))
	done
	echo -en "[38;5;256m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -en "[38;5;256m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -en "[38;5;256m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -en "[38;5;256m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -en "[38;5;256m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
	echo -e "[38;5;256m"$xxx": [48;5;"$xxx"m      [m  "
	((xxx +=1))
done

