#!/bin/bash


function __cmap1a()
{
	xxx=0
	echo -e "\n\nＢａｓｉｃ ｃｏｌｏｒｓ：\n"
	while [ "$xxx" -lt 17 ]; do
		while [ "$xxx" -lt 10 ]; do
			while [ "$xxx" -lt 8 ]; do
				echo -en "[38;5;256m "$xxx":[48;5;"$xxx"m       [m "
				((xxx +=1))
			done
			echo -e "BOLD / BRIGHT"
			echo -en "[38;5;256m "$xxx":[48;5;"$xxx"m       [m "
			((xxx +=1))
		done
		echo -en "[38;5;256m"$xxx":[48;5;"$xxx"m       [m "
		((xxx +=1))
	done
	echo -e "NORMAL"
}
